"use client";

import { useState } from "react";
import Link from "next/link";
import Script from "next/script";
import LandingNavbar from "../../components/LandingNavbar/LandingNavbar";
import { useAuth } from "../../contexts/AuthContext";
import { db } from "../../lib/firebase";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";

// Function to generate unique ticket ID in format "TKT-YYYYMMDD-XXX"
function generateTicketId() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const randomNum = String(Math.floor(Math.random() * 1000)).padStart(3, '0');
  return `TKT-${year}${month}${day}-${randomNum}`;
}

export default function ContactPage() {
  const [form, setForm] = useState({
    name: "",
    email: "",
    subject: "",
    message: "",
  });
  const [status, setStatus] = useState({ type: "idle", message: "" });
  const { user } = useAuth();

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((f) => ({ ...f, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Check if user is logged in
    if (!user) {
      setStatus({ type: "error", message: "Please log in to submit a support request." });
      return;
    }

    setStatus({ type: "loading", message: "Sending message..." });

    try {
      // Get the API base URL from environment (Firebase Functions)
      const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || '/api';
      
      // 1. Send email via Firebase Functions backend
      const emailResponse = await fetch(`${apiBaseUrl}/contact`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: form.name,
          email: form.email,
          subject: form.subject,
          message: form.message,
        }),
      });

      if (!emailResponse.ok) {
        const errorData = await emailResponse.json();
        throw new Error(errorData.error || 'Failed to send email');
      }

      // 2. Save to Firestore: support/{userId}/cases/{autoGeneratedId}
      const ticketId = generateTicketId();
      const now = new Date().toISOString();
      
      await addDoc(collection(db, 'support', user.uid, 'cases'), {
        // Existing fields
        name: form.name,
        email: form.email,
        subject: form.subject,
        message: form.message,
        timestamp: serverTimestamp(),
        status: 'open',
        
        // New fields
        ticketId: ticketId,
        priority: 'medium',
        category: 'general',
        assignedTo: null,
        assignedToName: null,
        updatedAt: serverTimestamp(),
        source: 'contact_form',
        responses: [],
        tags: [],
        emailNotifications: {
          userNotified: false,
          lastNotificationSent: null,
          notificationCount: 0
        },
        activityLog: [
          {
            action: 'created',
            timestamp: now,
            source: 'contact_form'
          }
        ]
      });

      setStatus({ type: "success", message: "Message sent successfully! We'll get back to you soon." });
      setForm({ name: "", email: "", subject: "", message: "" });
    } catch (err) {
      console.error('Error sending message:', err);
      setStatus({ type: "error", message: err.message || "Failed to send message. Please try again." });
    }
  };

  return (
    <>
      {/* Optional: Bootstrap JS for potential interactive components */}
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />

      {/* Landing Navbar for consistency with landing page */}
      <LandingNavbar containerClass="py-2" />

      {/* Header */}
      <header className="py-4 container mx-auto rounded-4 mt-3" style={{
        background: "linear-gradient(135deg, var(--bg-gradient-start), var(--bg-gradient-end))",
        color: "white",
        maxWidth: "1142px",
        paddingLeft: "calc(var(--bs-gutter-x) * 0.5)",
        paddingRight: "calc(var(--bs-gutter-x) * 0.5)"
      }}>
        <div className="container py-4">
          <div className="row align-items-center">
            <div className="col-lg-8">
              <h1 className="display-4 fw-bold mb-3">Contact Support</h1>
              <p className="lead mb-0" style={{ opacity: 0.95 }}>
                Have questions or need help? Send us a message and we'll get back to you.
              </p>
            </div>
          </div>
        </div>
      </header>
      {/* Contact Section (Dashboard-styled bordered container) */}
      <main className="container my-md-4 d-flex justify-content-center">
        {/* Constrain width to match LandingNavbar inner (1140px) */}
        <div className="w-100" style={{ maxWidth: "1140px" }}>
          {/* Gradient-border wrapper to highlight container borders (landing style) */}
          <div
            className="position-relative p-2 p-md-3 shadow"
            style={{
              background: "linear-gradient(90deg, #627FFF 0%, #23D2EE 100%)",
              borderRadius: "24px",
            }}
          >
            <div className="bg-white p-3 p-md-4" style={{ borderRadius: "20px" }}>
              <div className="row g-4">
                <div className="col-12 col-lg-7">
                  <div
                    className="card shadow-sm border"
                    style={{
                      background: '#F9FAFB',
                      borderColor: '#C2C2C2',
                      borderWidth: '2px',
                      borderRadius: '14px',
                    }}
                  >
                    <div className="card-body p-4 p-lg-5">
                      <h2 className="h4 mb-4">Send us an email</h2>
                      
                      {!user && (
                        <div className="alert alert-warning" role="alert">
                          <strong>Please log in</strong> to submit a support request. 
                          <Link href="/login" className="alert-link ms-1">Sign in here</Link>
                        </div>
                      )}
                      
                      {status.type === "success" && (
                        <div className="alert alert-success" role="alert">
                          {status.message}
                        </div>
                      )}
                      {status.type === "error" && (
                        <div className="alert alert-danger" role="alert">
                          {status.message}
                        </div>
                      )}
                      {status.type === "loading" && (
                        <div className="alert alert-info" role="alert">
                          {status.message}
                        </div>
                      )}
                      <form onSubmit={handleSubmit} className="needs-validation" noValidate>
                        <div className="row g-3">
                          <div className="col-12 col-md-6">
                            <label htmlFor="name" className="form-label">Name</label>
                            <input
                              type="text"
                              className="form-control"
                              id="name"
                              name="name"
                              placeholder="Your name"
                              value={form.name}
                              onChange={handleChange}
                              required
                            />
                          </div>
                          <div className="col-12 col-md-6">
                            <label htmlFor="email" className="form-label">Email</label>
                            <input
                              type="email"
                              className="form-control"
                              id="email"
                              name="email"
                              placeholder="you@example.com"
                              value={form.email}
                              onChange={handleChange}
                              required
                            />
                          </div>
                          <div className="col-12">
                            <label htmlFor="subject" className="form-label">Subject</label>
                            <input
                              type="text"
                              className="form-control"
                              id="subject"
                              name="subject"
                              placeholder="How can we help?"
                              value={form.subject}
                              onChange={handleChange}
                              required
                            />
                          </div>
                          <div className="col-12">
                            <label htmlFor="message" className="form-label">Message</label>
                            <textarea
                              className="form-control"
                              id="message"
                              name="message"
                              rows={6}
                              placeholder="Share a few details so we can assist you"
                              value={form.message}
                              onChange={handleChange}
                              required
                            />
                          </div>
                          <div className="col-12 d-flex align-items-center justify-content-between">
                            <small className="text-muted">We typically respond within 1 business day.</small>
                            <button type="submit" className="btn btn-primary px-4" disabled={status.type === "loading" || !user}>
                              {status.type === "loading" ? "Sending..." : "Send Message"}
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>

                <div className="col-12 col-lg-5">
                  <div
                    className="card shadow-sm h-100 border"
                    style={{
                      background: '#F9FAFB',
                      borderColor: '#C2C2C2',
                      borderWidth: '2px',
                      borderRadius: '14px',
                    }}
                  >
                    <div className="card-body p-4 p-lg-5">
                      <h3 className="h5 mb-3">Other ways to reach us</h3>
                      <p className="mb-4 text-muted">Our team is here to help you make the most of QueryFuel.</p>
                      <ul className="list-unstyled">
                        <li className="mb-3 d-flex align-items-start">
                          <i className="bi bi-envelope text-primary me-3 fs-5" aria-hidden></i>
                          <div>
                            <div className="fw-semibold">Email</div>
                            <div className="text-muted">support@queryfuel.io</div>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Landing Footer for consistency with landing page */}
    </>
  );
}
