export const data = {
  Islamabad: [
    "F-6",
    "F-7",
    "F-8",
    "F-9",
    "F-10",
    "F-11",
    "G-5",
    "G-6",
    "G-7",
    "G-8",
    "G-9",
    "G-10",
    "G-11",
    "H-8",
    "H-9",
    "I-8",
    "I-9",
    "I-10",
    "E-11",
    "D-12",
  ],
  Karachi: [
    "Korangi",
    "Gulshan-e-Iqbal",
    "Saddar",
    "North Nazimabad",
    "Defence Housing Authority",
    "Clifton",
    "Malir",
    "Gulistan-e-Jauhar",
    "Orangi Town",
    "Landhi",
    "PECHS",
    "Lyari",
    "Federal B Area",
    "Garden East",
    "Garden West",
    "Baldia Town",
    "Shah Faisal Colony",
    "Model Colony",
    "Liaquatabad",
    "Nazimabad",
  ],
  Lahore: [
    "Gulberg",
    "Model Town",
    "DHA",
    "Johar Town",
    "Wapda Town",
    "Bahria Town",
    "Cantt",
    "Garden Town",
    "Valencia",
    "Allama Iqbal Town",
    "Township",
    "Faisal Town",
    "Samanabad",
    "Cavalry Ground",
    "Shalimar",
    "Mozang",
    "Mughalpura",
    "Raiwind",
    "Green Town",
    "Shadman",
  ],
  Rawalpindi: [
    "Saddar",
    "Murree Road",
    "Chaklala",
    "Bahria Town",
    "DHA",
    "Satellite Town",
    "Westridge",
    "Lalazar",
    "Adiala Road",
    "Gulraiz",
    "Chakri",
    "Morgah",
    "Gulistan Colony",
    "Tench Bhatta",
    "Dhoke Kala Khan",
    "Range Road",
    "Scheme III",
    "Kotha Kalan",
    "Committee Chowk",
    "Commercial Market",
  ],
  Faisalabad: [
    "D-Ground",
    "Railway Road",
    "Satyana Road",
    "Peoples Colony",
    "Ghulam Muhammad Abad",
    "Susan Road",
    "Madina Town",
    "Gulistan Colony",
    "Kohinoor City",
    "Batala Colony",
    "Jinnah Colony",
    "Muslim Town",
    "Abdullah Pur",
    "Mansoorabad",
    "Chak Jhumra",
    "Canal Road",
    "Millat Town",
    "Samanabad",
    "Khurrianwala",
    "Jaranwala Road",
  ],
  Multan: [
    "Cantt",
    "Lodhran Road",
    "Boson Road",
    "Gulgasht Colony",
    "Mumtazabad",
    "Shalimar Colony",
    "Khanewal Road",
    "Garden Town",
    "New Multan",
    "Shah Rukn-e-Alam Colony",
    "Askari",
    "MDA Chowk",
    "Bosan Road",
    "Northern Bypass",
    "Masoom Shah Road",
    "Nawa Shehar",
    "Vehari Road",
    "Bahawalpur Road",
    "Dera Adda",
    "Qadirpur Rawan",
  ],
  Peshawar: [
    "Hayatabad",
    "Cantt",
    "University Town",
    "Gulbahar",
    "Tehkal",
    "Warsak Road",
    "Gulberg",
    "Saddar",
    "Islamia College",
    "Dabgari Gardens",
    "Hyatabad Phase 1",
    "Hyatabad Phase 2",
    "Hyatabad Phase 3",
    "Hyatabad Phase 4",
    "Hyatabad Phase 5",
    "Ring Road",
    "Charsadda Road",
    "GT Road",
    "Nasir Bagh Road",
    "Civil Quarters",
  ],
  Quetta: [
    "City Centre",
    "Cantt",
    "Jinnah Town",
    "Satellite Town",
    "Zarghoon Road",
    "Chiltan Housing Scheme",
    "Samungli Housing Scheme",
    "Model Town",
    "Killi Shabo",
    "Sariab Road",
    "Brewery Road",
    "Nawan Killi",
    "Airport Road",
    "Kuchlak",
    "Joint Road",
    "Shahbaz Town",
    "Pashtoonabad",
    "Hudd",
    "Mariabad",
    "Hazara Town",
  ],
  Gujranwala: [
    "Sialkot Road",
    "Wazirabad Road",
    "GT Road",
    "Model Town",
    "Peoples Colony",
    "Trust Colony",
    "Satellite Town",
    "Civil Lines",
    "DC Colony",
    "Gurjakh",
    "Khiali Shah Pur",
    "Aroop Town",
    "Chand Da Qila",
    "Baghbanpura",
    "Qila Mian Singh",
    "Shaheenabad",
    "Dhullay",
    "Wapda Town",
    "Royal Palm",
    "Muhafiz Town",
  ],
  Sialkot: [
    "Cantt",
    "Daska Road",
    "Sambrial Road",
    "Model Town",
    "Paris Road",
    "Aziz Bhatti Town",
    "Kashmir Road",
    "Defence Road",
    "Shahabpura",
    "Rang Pura",
    "Muhammadpura",
    "Gohadpur",
    "Hajipura",
    "Kotli Loharan",
    "Pasrur Road",
    "Sublime Chowk",
    "Allama Iqbal Town",
    "Railway Road",
    "Chawinda Road",
    "Aimenabad Road",
  ],
  Gujrat: [
    "GT Road",
    "Kharian Road",
    "Jhelum Road",
    "Bhimber Road",
    "Rehman Shaheed Road",
    "Bhimbher Road",
    "Jail Road",
    "Model Town",
    "Sargodha Road",
    "Kot Maira Road",
    "Mandvi Mohalla",
    "Shadman Colony",
    "Ali Town",
    "Gulshan Colony",
    "Wazirabad Road",
    "Shadman Colony",
    "Lakhanwal",
    "Jokalian",
    "Rehman Town",
    "Abbasi Town",
  ],
  Bahawalpur: [
    "Satellite Town",
    "Model Town",
    "Dera Nawab Sahib",
    "One Unit Colony",
    "Yazman Road",
    "Dubai Chowk",
    "Islami Colony",
    "Hashmi Garden",
    "Gulshan-e-Rahim",
    "Commercial Area",
    "Abbasia Town",
    "Lodhran Road",
    "Ahmadpur East Road",
    "Chak No.11",
    "Chak No.7",
    "Goth Mehrab",
    "Civil Lines",
    "Cantt",
    "Qaimpur",
    "Sama Satta",
  ],
  Sukkur: [
    "Airport Road",
    "Indus Highway",
    "Larkana Road",
    "Military Road",
    "Barrage Road",
    "Clock Tower",
    "Minara Road",
    "Queens Road",
    "Shikarpur Road",
    "Station Road",
    "Nishtar Road",
    "Lab-e-Mehran",
    "Bandar Road",
    "Tori Bangla",
    "Gharibabad",
    "Bachal Shah Miani",
    "New Pind",
    "Rohri",
    "Saleh Pat",
    "Pano Aqil",
  ],
  Larkana: [
    "Rato Dero",
    "Dokri",
    "Shahdadkot",
    "Sachal Colony",
    "Lahori Mohalla",
    "Naudero",
    "Bakrani",
    "Kambar",
    "Warah",
    "Nasirabad",
    "Pakistan Chowk",
    "Rice Canal Road",
    "Mohalla Mir Khan",
    "Allahabad",
    "Rashid Wagan Road",
    "Lahori Muhalla",
    "Baqapur",
    "Abdullah Shaikh",
    "Ali Akbar Shah",
    "Garelo",
  ],
  Abbottabad: [
    "Ayub Medical Complex",
    "PMA",
    "Nawanshehr",
    "Jinnahabad",
    "Mandian",
    "Kehal",
    "Supply",
    "Malikpura",
    "Bilal Town",
    "Habibullah Colony",
    "Jhangi",
    "Mir Pur",
    "Kakul",
    "Dhamtor",
    "Banda Pir Khan",
    "Havelian",
    "Narian",
    "Sherwan",
    "Namli Maira",
    "Langra",
  ],
  Sheikhupura: [
    "Faisalabad Road",
    "Lahore Road",
    "Sharaqpur Road",
    "Sargodha Road",
    "Farooqabad Road",
    "Jinnah Park",
    "Gulshan Colony",
    "Khan Colony",
    "Ghang Road",
    "Railway Road",
    "Ghulam Muhammad Abad",
    "Mian Colony",
    "Circular Road",
    "Kot Abdul Malik",
    "Ferozewala",
    "Muridke",
    "Narang Mandi",
    "Safdarabad",
    "Manawala",
    "Kharianwala",
  ],
  Mardan: [
    "Nowshera Road",
    "Charsadda Road",
    "Saidu Sharif Road",
    "Sheikh Maltoon Town",
    "Shankar",
    "Baghdada",
    "Par Hoti",
    "Muslimabad",
    "Bijligar",
    "Toru",
    "New Urbanization",
    "Katlang",
    "Takht Bhai",
    "Jalala",
    "Rustam",
    "Lundkhwar",
    "Kalu Khan",
    "Shahbaz Garhi",
    "Gujar Garhi",
    "Mayar",
  ],
  "Mirpur Khas": [
    "Mithi Road",
    "Nawabshah Road",
    "Digri Road",
    "Sindhri Road",
    "Tando Adam Road",
    "Satellite Town",
    "Heerabad",
    "Gharibabad",
    "Khan Colony",
    "Sindhi Muslim Society",
    "Baldia Colony",
    "Ali Housing Society",
    "Memons Colony",
    "Mir Colony",
    "Adam Town",
    "Fazal Town",
    "Chandnio Colony",
    "Eid Gah Road",
    "Jail Road",
    "Liaquat University",
  ],
  Hyderabad: [
    "Latifabad",
    "Qasimabad",
    "Preetabad",
    "Hussainabad",
    "Mubarak Colony",
    "Noorani Basti",
    "Bhitai Colony",
    "Citizen Colony",
    "Kotri",
    "Jamshoro",
    "Tando Allahyar",
    "Matiari",
    "Hala",
    "Tando Muhammad Khan",
    "Tando Jam",
    "Gulshan-e-Shahbaz",
    "Autobahn Road",
    "Saddar",
    "Hirabad",
    "Sarfaraz Colony",
  ],
  Sargodha: [
    "Block 1",
    "Block 2",
    "Block 3",
    "Block 4",
    "Satellite Town",
    "Muslim Bazaar",
    "Liaquat Colony",
    "Canal Colony",
    "University Road",
    "Civil Lines",
    "Khayaban-e-Sadiq",
    "Farooq Colony",
    "Muhammadi Colony",
    "Old Satellite Town",
    "Quaid-e-Azam Colony",
    "Aziz Bhatti Town",
    "Al-Raheem Valley",
    "Sillanwali",
    "Bhalwal",
    "Shahpur",
  ],

  "Ahmadpur East": [
    "Katchery Bazaar",
    "Mohalla Islam Ganj",
    "Mohalla Sadiqabad",
    "Satellite Town",
    "Shahwala Gate",
    "Muhammad Pur",
    "Mohalla Rahim Abad",
    "Noor Mahal Road",
    "College Road",
    "Bhutta Colony",
    "Mohalla Khokhar Pura",
    "Mohalla Baloch Pura",
    "Gharib Abad",
    "Cheema Colony",
    "Mohalla Sheikhan",
    "Eid Gah Road",
    "Bahawalpur Road",
    "Church Road",
    "Mohalla Qadirabad",
    "Mohalla Hassan Pura",
  ],
  Attock: [
    "Kamra",
    "Fauji Colony",
    "Jinnah Abad",
    "Pindi Gheb",
    "Hassanabdal",
    "Khaur",
    "Fateh Jang",
    "Jand",
    "Malik Mala",
    "Hazro",
    "Basal",
    "Hajishah",
    "Bahtar",
    "Jahanabad",
    "Bahadar Khan",
    "Mirza Potha",
    "Chhab",
    "Lawa",
    "Domel",
    "Khunda",
  ],
  Badin: [
    "Ward No. 1",
    "Ward No. 2",
    "Ward No. 3",
    "Ward No. 4",
    "Ward No. 5",
    "Tando Bago",
    "Talhar",
    "Matli",
    "Shaheed Fazil Rahu",
    "Golarchhi",
    "Khairpur Gambo",
    "Kadhan",
    "Golarchi",
    "Seerani",
    "Khoski",
    "Dai Jarkas",
    "Bughra Memon",
    "Peer Shahnawaz",
    "Kario Ghanwar",
    "Saman",
  ],
  Bahawalnagar: [
    "Model Town",
    "Satellite Town",
    "Islami Colony",
    "Officers Colony",
    "Faisal Colony",
    "Gulshan-e-Fareed",
    "Lodhran Basti",
    "Chishtian Road",
    "Minchinabad Road",
    "Fort Abbas Road",
    "Haroonabad Road",
    "McLeod Ganj",
    "Railway Housing Society",
    "Civil Lines",
    "Gulshan-e-Rahim",
    "Old Bahawalnagar",
    "Noor Mahal Colony",
    "Mohallah Qamar Garden",
    "Nai Abadi",
    "Iqbal Nagar",
  ],
  Bannu: [
    "Sokari Gate",
    "Shinkai",
    "Miryan",
    "Norar",
    "Mandan",
    "Domel",
    "Mamash Khel",
    "Surani",
    "Bakka Khel",
    "Baka Khel",
    "Hinjal",
    "Shamshi Khel",
    "Fatima Khel",
    "Azim Kala",
    "Ibrahim Zai",
    "Khojari",
    "Mira Khel",
    "Ghoriwala",
    "Dhoda",
    "Township",
  ],
  Bhakkar: [
    "Darya Khan",
    "Mankera",
    "Kaloor Kot",
    "Kaloorkot",
    "Jandanwala",
    "Notak",
    "Dullewala",
    "Kallur Kot",
    "Jhang City",
    "Chak 25",
    "Kotla Jam",
    "Behal",
    "Fazil Pur",
    "Pir Kot",
    "Daggar",
    "Daud Khel",
    "Gunjial",
    "Joya",
    "Chak Naurang",
    "Wahva",
  ],
  Bhimber: [
    "Barnala",
    "Jatlan",
    "Samahni",
    "Charohi",
    "Pir Anayyatullah Town",
    "Poona",
    "Bandala",
    "Soksan",
    "Panjeri",
    "Dab",
    "Moil",
    "Jogian",
    "Jabbi",
    "Khairowal",
    "Chaudhary Abad",
    "Pindi",
    "Mangla View",
    "Baghsar",
    "New City",
    "Islampura",
  ],
  Buner: [
    "Daggar",
    "Jowar",
    "Pir Baba",
    "Nagrai",
    "Chamla",
    "Gadezai",
    "Chagharzai",
    "Totalai",
    "Khudu Khel",
    "Salarzai",
    "Gokand",
    "Malka",
    "Elai",
    "Karapa",
    "Nawagai",
    "Koga",
    "Amazai",
    "Makhranai",
    "Ambela",
    "Bampokha",
  ],
  Chakwal: [
    "Talagang",
    "Choa Saiden Shah",
    "Kallar Kahar",
    "Lawa",
    "Balkassar",
    "Dhudial",
    "Buchal Kalan",
    "Chak Malook",
    "Chawli",
    "Dulmial",
    "Bhikhari Kalan",
    "Dalwal",
    "Karyala",
    "Mogla",
    "Nadanpur",
    "Mureed",
    "Karsal",
    "Chak Khushi",
    "Kot Sarang",
    "Dhoda",
  ],
  Charsadda: [
    "Tangi",
    "Utmanzai",
    "Turangzai",
    "Dargai",
    "Prang",
    "Shabqadar",
    "Rajjar",
    "Batkhela",
    "Prang Ghar",
    "Sherpao",
    "Hissada",
    "Dosehra",
    "Ghunda",
    "Dheri Zardad",
    "Mirza Dher",
    "Sardheri",
    "Mandani",
    "Umarzai",
    "Khazana",
    "Palai",
  ],
  Chiniot: [
    "Faisalabad Road",
    "Jhang Road",
    "Sargodha Road",
    "Chenab Nagar",
    "Lalian",
    "Bhawana",
    "Rajoya",
    "Ahmad Nagar",
    "Shah Jewna",
    "Allah Yar",
    "Kot Ismail",
    "Muzaffar Colony",
    "Aminabad",
    "Chiniot Sadar",
    "Tehsil Chowk",
    "Punj Grain",
    "Bhawana Road",
    "Rai Chand",
    "Thatta Muhammad",
    "Chenab Chowk",
  ],
  Chishtian: [
    "Railway Road",
    "College Road",
    "Bahawalnagar Road",
    "Sadiq Colony",
    "Fort Abbas Road",
    "Ghalla Mandi",
    "Arifwala Road",
    "Burewala Road",
    "Faqirwali",
    "Bahawalnagar Bypass",
    "Canal Colony",
    "Tariq Abad",
    "Madni Colony",
    "Gulberg",
    "Gulshan-e-Madina",
    "New City",
    "Peoples Colony",
    "Lahore Road",
    "Muslim Town",
    "Sabzi Mandi",
  ],
  Chitral: [
    "Ayun",
    "Drosh",
    "Garam Chashma",
    "Mastuj",
    "Booni",
    "Torkho",
    "Mulkhow",
    "Lon",
    "Barenis",
    "Golen",
    "Madaklasht",
    "Terich",
    "Laspur",
    "Oveer",
    "Yarkhun",
    "Shoghor",
    "Karimabad",
    "Arkari",
    "Lotkuh",
    "Khot",
  ],
  Dadu: [
    "Bhan Syedabad",
    "Johi",
    "KN Shah",
    "Mehar",
    "Khairpur Nathan Shah",
    "Sita Road",
    "Phulji Station",
    "Radhan",
    "Gozo",
    "Paat Sharif",
    "Tando Rahim Khan",
    "Chaunro",
    "Drigh Bala",
    "Bothro",
    "Parya Road",
    "Makhdoom Bilawal",
    "Khanpur",
    "Gozo",
    "Khudabad",
    "Moundar",
  ],
  Daska: [
    "Qila Kalarwala",
    "Satrah",
    "Motra",
    "Jamkey Cheema",
    "Glotian",
    "Kot Daska",
    "Bhopalwala",
    "Kingra",
    "Gunna Kalan",
    "Sajowal",
    "Shakar Garh",
    "Dharam Kot",
    "Badiana",
    "Sohadra",
    "Bambanwala",
    "Chahoor",
    "Kotli Loharan",
    "Adamke",
    "Kotli Bahram",
    "Mundeke",
  ],
  "Dera Ghazi Khan": [
    "Block 1",
    "Block 2",
    "Block 3",
    "Block 4",
    "Block 5",
    "Block 6",
    "Block 7",
    "Block 8",
    "Block 9",
    "Sakhi Sarwar",
    "Kot Chutta",
    "Taunsa",
    "Vehova",
    "Kot Mubarak",
    "Tribal Area",
    "Noorpur",
    "Choti Zareen",
    "Tibbi Qaisrani",
    "Kot Qaisrani",
    "Basti Fauja",
  ],
  "Dera Ismail Khan": [
    "Mohalla Jadeed",
    "Tank Adda",
    "Cantt",
    "Sheikh Yousaf",
    "Zafarabad",
    "Dera Town",
    "Madina Colony",
    "Muryali",
    "Himat",
    "Gomal University",
    "Parova",
    "Paharpur",
    "Kulachi",
    "Daraban",
    "Chashma",
    "Yarik",
    "Draban",
    "Tehsil Darazinda",
    "Kiri Khaisore",
    "Kot Sultan",
  ],
  Dina: [
    "Housing Colony",
    "Railway Road",
    "Main Bazaar",
    "Civil Lines",
    "Chakwal Road",
    "Domeli",
    "Sohawa",
    "Sara-e-Alamgir",
    "Jatli",
    "Mandra",
    "Chakri",
    "Jarmot",
    "Kala Gujran",
    "Bhagwal",
    "Dadyal",
    "Mirpur",
    "Islamgarh",
    "Mangla",
    "Khaliqabad",
    "Dhan Gali",
  ],
  Eidgah: [
    "Poonch",
    "Mendhar",
    "Surankot",
    "Haveli",
    "Hajira",
    "Rawlakot",
    "Pallandri",
    "Bagh",
    "Dhirkot",
    "Thorar",
    "Abbaspur",
    "Mandhole",
    "Rawalakot",
    "Tarar Khal",
    "New City",
    "Chattar",
    "Sehnsa",
    "Hari Ghel",
    "Khai Gala",
    "Rahara",
  ],
  Fatehjang: [
    "Dhrek Mohri",
    "Thatti Gujran",
    "Ganji",
    "Kot Fateh Khan",
    "Dandi",
    "Dhurnal",
    "Kamrial",
    "Malal",
    "Jand",
    "Thoa Khalsa",
    "Bahtar",
    "Basal",
    "Chauntra",
    "Jhari Kas",
    "Khunda",
    "Makhad",
    "Pindi Gheb",
    "Gadwal",
    "Kamalpur",
    "Hassan Abdal",
  ],
  Ghotki: [
    "Adilpur",
    "Daharki",
    "Mirpur Mathelo",
    "Khangarh",
    "Ubauro",
    "Qadirpur",
    "Garhi Chakar",
    "Garhi Yaseen",
    "Khanpur Mahar",
    "Dhingano Mahesar",
    "Jam Sahib",
    "Yaro Lund",
    "Faiz Ganj",
    "Reti",
    "Jarwar",
    "Khan Pur",
    "Raharki",
    "Kumb",
    "Khanpur Mahar",
    "Ghotki Bypass",
  ],
  Gilgit: [
    "Jutial",
    "Kashrote",
    "Khomer",
    "Basin",
    "Danyore",
    "NLI Colony",
    "Nagral",
    "Sakwar",
    "Konodas",
    "Barmas",
    "Parri",
    "Majini Muhalla",
    "Ampheri",
    "Sultanabad",
    "Oshikhandas",
    "Nagaral",
    "Harpoon",
    "Sonikot",
    "Mujahidabad",
    "Yasin",
  ],
  Gojra: [
    "Chak 95",
    "Chak 372",
    "Chak 279",
    "Mauza Kot Sindhu",
    "Chak 378",
    "Muhammad Wala",
    "Chak 381",
    "Chak 384",
    "Chak 383",
    "Chak 379",
    "Chak 310",
    "Chak 311",
    "Chak 312",
    "Chak 313",
    "Mauza Phalaya",
    "Chak 316",
    "Chak 317",
    "Chak 319",
    "Chak 320",
    "Toba Tek Singh Road",
  ],
  "Gujar Khan": [
    "Daultala",
    "Mandrah",
    "Qazian",
    "Bhai Khan",
    "Sukho",
    "Jatli",
    "Kauntrila",
    "Mandra",
    "Mankiala",
    "Bewal",
    "Hamot",
    "Girjaakh",
    "Dhok Pathan",
    "Doberan Kalan",
    "Islampura",
    "Kashmir Colony",
    "Dhamali",
    "Bagh Dheri",
    "Mohra Balochan",
    "Sara-e-Kharbooza",
  ],
  Gwadar: [
    "Javed Complex",
    "Singhar Housing",
    "New Town",
    "Industrial Area",
    "Port Area",
    "Balochabad",
    "Mullah Band",
    "Sur Bandar",
    "Padi Zur",
    "Shabi",
    "Marine Drive",
    "Airport Road",
    "Thana Road",
    "Dasht",
    "Kushkosh",
    "Jawani",
    "Nalaint",
    "Jiwani",
    "Suntsar",
    "Pishukan",
  ],
  Hafizabad: [
    "Kassoki",
    "Kot Nakka",
    "Madhrianwala",
    "Sukheki",
    "Thatha Ghulam Nabi",
    "Vanike Tarar",
    "Pindi Bhattian",
    "Alipur Chattha",
    "Jalalpur Bhattian",
    "Kaleke Mandi",
    "Kolo Tarar",
    "Kot Sarwar",
    "Mangat Neecha",
    "Rasulpur Tarar",
    "Thatha Aziz Khan",
    "Behlolpur",
    "Kot Nakka",
    "Thatha Khalil",
    "Burana",
    "Saidan Shah",
  ],
  Haripur: [
    "Ghazi",
    "Khanpur",
    "Khalabat Township",
    "Sarai Saleh",
    "Baldher",
    "Rehana",
    "Kot Najeebullah",
    "Hattar",
    "Panian",
    "Pandak",
    "Beer",
    "Bandi Sher Khan",
    "Bagra",
    "Najafpur",
    "Pharhari",
    "Kotnajibullah",
    "Dingi",
    "Kholian Bala",
    "Seria",
    "Barkot",
  ],
  Haroonabad: [
    "Faqirwali",
    "Bahawalnagar Road",
    "Chishtian Road",
    "Fortabbas Road",
    "Dahranwala",
    "Minchin Abad Road",
    "Model Town",
    "Officers Colony",
    "Satellite Town",
    "College Road",
    "Railway Road",
    "Muhajir Colony",
    "Housing Colony",
    "Sadiq Colony",
    "Canal Colony",
    "Shahbaz Colony",
    "Mohalla Khalid Bin Waleed",
    "Mohalla Rasheedabad",
    "Muhammadi Colony",
    "Mubarak Colony",
  ],
  Hasilpur: [
    "Mandi Town",
    "Tibba Badar Sher",
    "Chak 58",
    "Chak 59",
    "Chak 60",
    "Chak 61",
    "Chak 112",
    "Chak 114",
    "Chak 115",
    "Chak 116",
    "Chak 123",
    "Chak 124",
    "Chak 148",
    "Chak 149",
    "Chak 150",
    "Chishtian Road",
    "College Road",
    "Bahawalpur Road",
    "Yazman Road",
    "Minchinabad Road",
  ],
  "Haveli Lakha": [
    "Chak 7",
    "Chak 8",
    "Chak 9",
    "Chak 10",
    "Chak 11",
    "Chak 12",
    "Chak 13",
    "Chak 14",
    "Chak 15",
    "Chak 16",
    "Qaboola",
    "Dipalpur",
    "Hujra Shah Muqeem",
    "Pakpattan Road",
    "Okara Road",
    "Sahiwal Road",
    "Basirpur",
    "Wasewala",
    "Arifwala",
    "Bahawalnagar Road",
  ],
  Hub: [
    "Industrial Area",
    "Gulshan-e-Saeed",
    "Gulshan-e-Madina",
    "Lakhra",
    "Gadani",
    "Winder",
    "Uthal",
    "Kanraj",
    "Dureji",
    "Khuda Bux Colony",
    "Gaddani Beach",
    "Pathra",
    "Alidad Goth",
    "Abdul Hakeem Goth",
    "Changli",
    "Rais Goth",
    "Goth Murad",
    "Goth Ibrahim",
    "Bhawani",
    "Sakran",
  ],
  Islamabad: [
    "F-6",
    "F-7",
    "F-8",
    "F-9",
    "F-10",
    "F-11",
    "G-5",
    "G-6",
    "G-7",
    "G-8",
    "G-9",
    "G-10",
    "G-11",
    "H-8",
    "H-9",
    "I-8",
    "I-9",
    "I-10",
    "E-11",
    "D-12",
  ],
  "Jalalpur Jattan": [
    "Barnala Road",
    "Dinga Road",
    "Kharian Road",
    "Kotla Road",
    "Mandi Bahauddin Road",
    "Miana Gondal Road",
    "Phalia Road",
    "Jhelum Road",
    "Chak Akbarabad",
    "Chak Muhammad Yar",
    "Chak Nizam",
    "Chak Qazi",
    "Chak Shireen",
    "Chak Syed Muhammad",
    "Dhera",
    "Gojra",
    "Kori",
    "Malakwal",
    "Mohra Shahan",
    "Shahdiwal",
  ],
  "Jalalpur Pirwala": [
    "Lodhran Road",
    "Bahawalpur Road",
    "Shujabad Road",
    "Old City",
    "Ali Wahan",
    "Basti Malook",
    "Jhangar Shah",
    "Khan Bela",
    "Khayaban-e-Sarwar",
    "Langer Sarai",
    "Mahmood Kot",
    "Mud Ghalwan",
    "Patti Sadaat",
    "Qasba Marral",
    "Rangeelpur",
    "Shamsabad",
    "Sher Shah",
    "Thatha Sadiqabad",
    "Wahi Pandhi",
    "Zakariya Town",
  ],
  Jaranwala: [
    "Main Bazaar",
    "College Road",
    "Satiana Road",
    "Samundri Road",
    "Chak 97",
    "Chak 237",
    "Chak 238",
    "Chak 239",
    "Chak 240",
    "Chak 241",
    "Chak 242",
    "Chak 243",
    "Chak 244",
    "Chak 245",
    "Chak 246",
    "Chak 247",
    "Chak 248",
    "Faisalabad Road",
    "Khichian",
    "Lahore Road",
  ],
  Jehangira: [
    "GT Road",
    "Kabul River",
    "Tarbela Road",
    "Swabi Road",
    "College Road",
    "Mohallah Shah Gul",
    "Mohallah Topi Khel",
    "Mohallah Naulakhi",
    "Mohallah Bandar",
    "Mohallah Fatehabad",
    "Mohallah Hameedan",
    "Mohallah Khatki",
    "Mohallah Mubarakabad",
    "Mohallah New Abadi",
    "Mohallah Rashidabad",
    "Mohallah Sethian",
    "Mohallah Sheikhabad",
    "Mohallah Suriabad",
    "Mohallah Topian",
    "Mohallah Zaman Pura",
  ],
  Jhelum: [
    "Cantt",
    "Civil Lines",
    "Kala Gujran",
    "Dina",
    "GT Road",
    "Mangla Colony",
    "Chak Jamal",
    "Chak Khasa",
    "Chak Shadi",
    "Chotala",
    "Dharyala Jalap",
    "Dhok Hukamdad",
    "Dhok Pir Bux",
    "Domeli",
    "Gharibwal",
    "Jalalpur Sharif",
    "Pind Dadan Khan",
    "Sarai Alamgir",
    "Sohawa",
    "Sanghoi",
  ],
  Jiwani: [
    "Bandri Mohalla",
    "Ismaili Mohalla",
    "Machi Mohalla",
    "Goth Panjgur",
    "Baloch Colony",
    "Fish Harbor",
    "Gwadar Road",
    "Iran Border",
    "Konarak",
    "Naval Base",
    "New Town",
    "Nok Kundi",
    "Old Town",
    "Pishukan",
    "Raees Colony",
    "Suntsar",
    "Washbood",
    "West Bay",
    "Jiwani Airport",
    "Jiwani Point",
  ],
  Kalat: [
    "Main Bazaar",
    "Shahi Bazaar",
    "Mangochar",
    "Mastung Road",
    "Surab Road",
    "Johan",
    "Iskalkoo",
    "Chappar",
    "Manguchar",
    "Nichargh",
    "Rodinjo",
    "Zehri",
    "Sheikh Wasil",
    "Gazg",
    "Sundrani",
    "Surmai",
    "Habibani",
    "Isplinji",
    "Pandran",
    "Lakhurian",
  ],
  Kamalia: [
    "Chak 711",
    "Chak 712",
    "Chak 713",
    "Chak 714",
    "Chak 715",
    "Chak 716",
    "Chak 717",
    "Chak 718",
    "Chak 719",
    "Chak 720",
    "Chak 721",
    "Chak 722",
    "Chak 723",
    "Chak 724",
    "Chak 725",
    "Chichawatni Road",
    "Chak Bandi Road",
    "Toba Tek Singh Road",
    "Pir Mahal Road",
    "Shorkot Road",
  ],
  Kamra: [
    "Kamra Cantt",
    "PAF Base",
    "Jhatla",
    "Zaryab Colony",
    "Bilal Town",
    "Dhok Gora",
    "Malik Pura",
    "Kamra Kalan",
    "Bhadana",
    "Dobian",
    "Kamra Khurd",
    "Mianwala",
    "Mohallah Farooq-e-Azam",
    "Mohallah Muslim Colony",
    "Mohallah Shaheen Town",
    "Pind Suleman",
    "Ranial",
    "Samundari",
    "Shahana",
    "Wasti",
  ],
  Kandhkot: [
    "Katcha Area",
    "Main Bazaar",
    "Bagri Mohalla",
    "Gul Mohammad Bhutto",
    "Muhammad Khan Bhutto",
    "New Kandhkot",
    "Old Kandhkot",
    "Station Road",
    "Tangwani",
    "Allah Abad",
    "Baho Khan Jatoi",
    "Ghouspur",
    "Haibat Bhutto",
    "Jamal Shah",
    "Kashmore",
    "Malir",
    "Mauladad",
    "Mir Sohrab Khan",
    "Pir Bux",
    "Zorgarh",
  ],
  Karak: [
    "Banda Daud Shah",
    "Bogara",
    "Darra Tang",
    "Gurguri",
    "Jehangiri",
    "Khurum",
    "Latambar",
    "Manki Sharif",
    "Nari Panos",
    "Palosa Sar",
    "Sabir Abad",
    "Takht-e-Nasrati",
    "Terri",
    "Bahadar Khel",
    "Ghundi",
    "Isak Chountra",
    "Jatta Ismail Khel",
    "Khushal Garh",
    "Mitha Khel",
    "Nar",
  ],
  Kasur: [
    "Fatehgarh Road",
    "Chunian Road",
    "Deepalpur Road",
    "Allahabad",
    "Raja Jang",
    "Khudian",
    "Mustafabad",
    "Kanganpur",
    "Pattoki",
    "Kot Radha Kishan",
    "Nathoki",
    "Sarai Mughal",
    "Ellahabad",
    "Kot Murad Khan",
    "Kot Haleem",
    "Jamber",
    "Khuddian",
    "Phool Nagar",
    "Manga Mandi",
    "Habibabad",
  ],
  Khairpur: [
    "Ghambat",
    "Hingorja",
    "Piryaloi",
    "Kot Diji",
    "Thari Mirwah",
    "Kingri",
    "Sobhodero",
    "Faiz Ganj",
    "Mirwah",
    "Gambat",
    "Khuhra",
    "Ahmedpur",
    "Therhi",
    "Ranipur",
    "Nara",
    "Pacca Chang",
    "Setharja",
    "Tando Masti",
    "Baqi Khan Pahore",
    "Shah Waliullah Town",
  ],
  Khanewal: [
    "Abdul Hakeem",
    "Jahanian",
    "Kabirwala",
    "Mian Channu",
    "Tulamba",
    "Chak 88",
    "Chak 89",
    "Chak 90",
    "Chak 91",
    "Chak 92",
    "Chak 93",
    "Chak 94",
    "Chak 95",
    "Chak 96",
    "Chak 97",
    "Chak 98",
    "Chak 99",
    "Chak 100",
    "Makhdoom Pur",
    "Old Khanewal",
  ],
  Khanpur: [
    "Ahmedpur",
    "Chachran Sharif",
    "Feroza",
    "Liaquat Road",
    "Machka",
    "Rahim Abad",
    "Sadiqabad",
    "Tando Jharak",
    "Tranda Muhammad Panah",
    "Main Bazaar",
    "Ghareebabad",
    "Gorgage Colony",
    "Makhan Colony",
    "Mehboob Colony",
    "Mubarak Colony",
    "Muslim Colony",
    "Nawababad",
    "Rehmat Colony",
    "Satellite Town",
    "Shah Jamal Colony",
  ],
  Kharian: [
    "Baghowal",
    "Bhangra",
    "Bhimber",
    "Dinga",
    "Garha Mor",
    "Kotli Loharan",
    "Lala Musa",
    "Langah",
    "Malikwal",
    "Mangla",
    "Nonar",
    "Pahrianwali",
    "Parhana",
    "Phalia",
    "Rasul",
    "Sahna",
    "Sarai Alamgir",
    "Sarkal",
    "Shadiwal",
    "Thatha",
  ],
  Khushab: [
    "Hadali",
    "Jauharabad",
    "Mitha Tiwana",
    "Noorpur Thal",
    "Quaidabad",
    "Adhi Kot",
    "Chak 44",
    "Chak 46",
    "Chak 47",
    "Chak 48",
    "Chak 50",
    "Chak 51",
    "Chak 52",
    "Chak 54",
    "Chak 56",
    "Chak 57",
    "Chak 58",
    "Chak 60",
    "Choa Ganj Ali Shah",
    "Soon Valley",
  ],
  Khuzdar: [
    "Aranji",
    "Baghbana",
    "Bela",
    "Chapri",
    "Darbelo",
    "Ferozabad",
    "Gaddani",
    "Gresha",
    "Karkh",
    "Korajo",
    "Kuzdar",
    "Moola",
    "Naach",
    "Nal",
    "Nall",
    "Ornach",
    "Saroona",
    "Surab",
    "Wadh",
    "Zehri",
  ],
  Kohat: [
    "Babri Banda",
    "Chor Lakki",
    "Darra Adam Khel",
    "Gumbat",
    "Hangu",
    "Jarma",
    "Junglekhel",
    "Kaghazai",
    "Karak",
    "Lachi",
    "Raisan",
    "Shakardarra",
    "Togh Bala",
    "Ustarzai",
    "Zarghun Khel",
    "KDA Township",
    "Kohat Cantt",
    "PAF Base",
    "Togh Sarai",
    "University Town",
  ],
  Kohlu: [
    "Barkhan",
    "Chattar",
    "Dehpal",
    "Grisani",
    "Haji Bugti Mohalla",
    "Kahan",
    "Karmanzai",
    "Kashiev",
    "Kharost",
    "Kori",
    "Lehri",
    "Mawand",
    "Nasirabad",
    "Nisao",
    "Oriani",
    "Phailag",
    "Rakhni",
    "Sangsila",
    "Tambo",
    "Torki",
  ],
  "Kot Addu": [
    "Budh",
    "Chak Manu",
    "Chowk Sarwar Shaheed",
    "Daira Din Panah",
    "Darya Khan",
    "Fazilpur",
    "Ghazipur",
    "Gurmani",
    "Jatoi",
    "Kacha Khuh",
    "Khangarh",
    "Mana Ahmadani",
    "Qasba Gujrat",
    "Rangpur",
    "Sanawan",
    "Sinawan",
    "Thatha Gurmani",
    "Thul Kamoka",
    "Muhammadpur",
    "Ali Pur",
  ],
  Kotli: [
    "Charhoi",
    "Darra Sher Khan",
    "Fatehpur Thakiala",
    "Khuiratta",
    "Nakyal",
    "Sehnsa",
    "Anderla",
    "Bagh Kotli",
    "Barali",
    "Chawala",
    "Dhanna",
    "Duliah Jattan",
    "Jaandi",
    "Kalyal",
    "Karela",
  ],
};
